columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  createButtonLabel: 'Add block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 501d1bf0-a6b7-4518-9e16-52e7b250d894 # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 553fa78f-c047-4fcc-a026-fd44d2db2651 # Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
