dateModified: 1763995928
email:
  fromEmail: pessimo@posteo.net
  fromName: crafty
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1bbcfb83-323f-44d1-89db-a7e3a995cfe1: 'Public Schema' # Public Schema
    3e4eb5c2-aa9b-44b1-882c-7432f09816d4: crafty # crafty
    d9505feb-37aa-49c1-a4e1-3ea3bb97a5eb: crafty # crafty
system:
  edition: solo
  live: true
  name: crafty
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
